### ISSUE TITLE
Cell Click Time issue (and others)

### ISSUE THREAD

**Issue by APusch-Tenno** [danheron/Heron.MudCalendar#160] opened 2024-08-15 10:08 UTC
hello,

yesterday I noticed, that when I click on a cell, the time is completely incorrect:

![grafik](https://github.com/user-attachments/assets/b0ef1fa5-dee2-4830-8104-794b5bd61291)

I don't even know where the odd minutes are coming from, but they are changing according to the interval.
I checked both my old testproject and your newest solution, which don't show this problem, so again, I'm not asking you to accommodate my programming mistakes, I am just kindly asking you to have a look and point me at the areas, where my project does something wrong.

I know I have made a few changes in your project, but these are mainly "optical".

And I still have the disappeared time marker, which I still don't know what caused it to disappear.
I kept manually updating your project files with WinMerge, so I don't overwrite my changes and also because I can't update to MudBlazor 7 yet.

Another issue I sporadically have is when I change the current week with the arrows, sometimes the click is not going through and I have to click a second time (tried waiting longer after each click).

I have created a new testproject and removed all irrelevant things:

[MudCalenderTest2.zip](https://github.com/user-attachments/files/16623998/MudCalenderTest2.zip)

Thanks in advance for your support.

**Comment by danheron** [comment] 2024-08-16 07:17
The problem is that the CurrentDay property expects a Date but you are passing a Date/Time.  If you change

```C#
DateTime _currentDay = DateTime.Now;
```
to
```C#
DateTime _currentDay = DateTime.Today;
```

Then it will work.

However I regard this as a bug in MudCalendar so I will fix it so that it still works even if you pass a Date/Time.


The disappearing Time Marker is because you have merged changes I made for MudBlazor 7 without actually using MudBlazor 7.  MudBlazor 7 has quite a few breaking changes.  One change was renaming the colour 'grey' to 'gray'.

MudCalendar now uses var(--mud-palette-gray-default) for the time marker.  In your project you should change this back to var(--mud-palette-grey-default)


The problem with the next week button seems to be only in work week view.  It seems to be only advancing the date by 5 days.  I will create a new issue for this.

**Comment by APusch-Tenno** [comment] 2024-08-16 07:35
Thank you so much!

Time marker is working again and time on click is also correct now (which fixed another issue I forgot to mention as well - initial loading of events didn't work only when switching the week, which can be explained now by the false date value).

I was aware of the breaking changes, because I actually tried to switch to MudBlazor 7 a few times, but because of other dependencies, I have to wait until these are updated.
I must have missed the change to gray during WinMerge compares, because now that you mentioned it, I know that this was one of the changes.
I always went back to a copy of the project and not reversed the changes for 7 to not have such a problem, but this one probably slipped through during an update.

Thanks again!

**Closed** 2024-08-16 13:17 UTC
Labels: bug
